### ISSUE TITLE
Create a configuration layer that helps make DKAN Starter more extensible

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan_starter#349]
## Description
I was hoping to open the conversation on the development of a configuration layer that can help to make the DKAN starter more extensible for other hosting environments.

One example: having the ability to configure the location of the docroot. Some hosting environments are very prescriptive about this. Being able to set this would help being able to use DKAN starter on a variety of different platforms.

Another example: Pantheon uses Drops. The setting of "core" could be Drops or could be Drupal core. It would be cool to have the option to select which one.

## Steps to Reproduce
n/a

## Acceptance Criteria
This is an ongoing ticket. I think initially would be seeing if we could use to DKAN Starter on a platform outside of Acquia 

## Subtasks

- [ ] Identify a high priority platform to explore
- [ ] Identify configuration that differs from current scripts
- [ ] Implement configuration layer (YML processor) and persistent settings format (e.g. YML file)
- [ ] Implement the diff'd configuration identified in step 2, set defaults to current option
- [ ] Add sample configuration files per platform that can be copied per platform

## Results

The current DevOps scripts can be configured to work with a high priority hosting platform

**Comment by dkinzer** [comment]
I think this is a great idea.  I propose that we add a new section to the `config/config.yml` reconfigure the files as part of the `ahoy build config` process dependent on configuration.

**Comment by dafeder** [comment]
We have the beginnings of this in DKAN Tools, and will build on it as the need arises. Closing.
