### ISSUE TITLE
Circle to use DKAN Docker Containers

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan_starter#494]
## Description
Upgrade our tests to use Circle 2 and use our local container files.

I'm starting in dkan_starter because there was already a PR for this but this will be ported to DKAN as well.

## Acceptance Criteria
DKAN tests work on CircleCI 2 using the same docker containers we are using locally.

## Subtasks

- [x] update to version 2
- [x] get docker compose working (using our own containers)
- [x] get parallelism working
- [ ] get caching working
- [x] get all tests passing

PR is here: #495

**Comment by acouch** [comment]
I have an updated PR #495 

The following are failing:

### Harvest
- [ ] features/dkan_harvest.feature:145

### Rest API
- [ ] features/dataset_rest_api.feature:24
- [ ] features/dataset_rest_api.feature:35
- [ ] features/dataset_rest_api.feature:53
- [ ]  features/dataset_rest_api.feature:64
- [ ] features/dataset_rest_api.feature:73
- [ ]  features/dataset_rest_api.feature:86
- [ ] features/dataset_rest_api.feature:97

### Fast Import
- [ ] features/datastore_fast_import.feature:36
- [ ] features/datastore_fast_import.feature:53
- [ ] features/datastore_fast_import.feature:68
    features/datastore_fast_import.feature:83

**Comment by acouch** [comment]
connects #476 
connects #495

**Comment by janette** [comment]
@acouch just looking at the circleci output, the dataset rest api errors could be the different log in for dkan_starter.
The datastore issues are a mix of exceeding 30 second time limit and not seeing things, looks like there is nothing in the artifacts tab, is that something that needs to be enabled?

I'll build locally so I can give a better report.

**Comment by acouch** [comment]
The harvest fails for me locally too. I get "<h1 class="page-header">Caching source and preparing Harvest preview...</h1>" instead of the page in the screenshot.

**Comment by janette** [comment]
@acouch  that is just a timing issue, the test is too slow in circle
![test-failure-screenshot-2018-04-19-14-47-32_i-should-see-the-success-message--harvest-source-source-1-has-been-created--](https://user-images.githubusercontent.com/314172/39011954-946a82aa-43d8-11e8-8a38-99522ee720d8.png)
